name: Publish Docker image

on:
  push:
    branches:
      - main
      - cepgen-*
#  release:
#    type: [ published ]

jobs:
  push_to_registry:
    name: Push HGCAL CI Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: laufor/hgcal_ci_images:latest
