name: Publish Docker image

on:
  push:
    branches:
      - main
      - cepgen-*

jobs:
  push_to_registry:
    name: Push CI Docker image to DockerHub
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: laufor/ci-images:${{ extract_branch.outputs.branch }}
    runs-on: ${{ steps.extract_branch.outputs.branch }}
